FROM node:lts-alpine as build
WORKDIR /app
ENV VITE_API_URL=https://carrier.logicore.ru/api
ENV VITE_API_WS_URL=https://carrier.logicore.ru
ENV VITE_STATIC_URL=https://carrier.logicore.ru  
COPY package*.json ./
RUN npm ci
COPY . .
RUN npm run build

FROM nginx:stable-alpine
COPY alfa.nginx.conf /etc/nginx/nginx.conf
COPY --from=build /app/dist /usr/share/nginx/html
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
