version: '3.8'
services:
  nginx_todo_app:
    name: transport_client
    image: nginx
    restart: always
    ports:
      - '8002:80'
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./dist:/var/www/html
