export const PIVOT_HEADERS = [
  { value: '_rowNumber', title: '№', sortable: false, width: '30px', align: 'right' },
  { title: 'Водитель', value: '_driverName', sortable: false, width: '350px' },
  {
    title: 'Рейсы',
    value: '_count',
    sortable: true,
    width: '100px',
    align: 'right',
    _total: 'sum',
    field: 'totalCount',
  },
  {
    title: 'Часы',
    value: 'duration',
    sortable: true,
    width: '100px',
    align: 'right',
    _total: 'sum',
  },
  {
    title: 'Ставка',
    value: 'base',
    sortable: true,
    width: '100px',
    align: 'right',
    _total: 'sum',
  },
  {
    title: 'Простой',
    value: 'waiting',
    sortable: true,
    width: '100px',
    align: 'right',
    _total: 'sum',
  },
  {
    title: 'Доплата',
    value: 'payment',
    sortable: true,
    width: '100px',
    align: 'right',
    _total: 'sum',
  },
  {
    title: 'Возврат',
    value: 'returnSum',
    sortable: true,
    align: 'right',
    width: '100px',
    _total: 'sum',
  },
  {
    title: 'Доп.точки',
    value: 'additionalPointsSum',
    sortable: true,
    align: 'right',
    width: '100px',
    _total: 'sum',
  },
  {
    title: 'Итого',
    value: 'totalSum',
    sortable: true,
    align: 'right',
    width: '120px',
    _total: 'sum',
  },
  {
    title: 'Оценка',
    value: 'avgGrade',
    sortable: true,
    width: '100px',
    align: 'right',
  },
  {
    value: 'padding',
    title: '',
    width: '20px',
    sortable: false,
  },
]

export const DRIVER_DETAILS_HEADERS = [
  { value: '_rowNumber', title: '№', sortable: false, width: '30px', align: 'right' },
  { title: 'Дата рейса', value: '_orderDate', sortable: false },
  { title: 'Грузовик', value: '_truckRegNum', sortable: false },
  { title: 'Прицеп', value: '_trailerRegNum', sortable: false },
  { title: 'Клиент', value: '_clientName', sortable: false },
  { title: 'Погрузка', value: '_loadingAddressesStr', sortable: false },
  { title: 'Выгрузка', value: '_unloadingAddressesStr', sortable: false },
  { title: 'Тип рейса', value: 'orderTypeStr', sortable: false },

  {
    title: 'Тип грузополучателя',
    value: '_consigneeType.text',
    sortable: false,
  },
  {
    title: 'Тип базового тарифа',
    value: '_baseTariffTypeStr',
    sortable: false,
  },
  {
    title: 'База',
    value: 'base',
    sortable: false,
    align: 'right',
    _total: 'sum',
  },
  {
    title: 'Простой',
    value: 'waiting',
    sortable: false,
    align: 'right',
    _total: 'sum',
  },
  {
    title: 'Возврат',
    value: 'returnSum',
    sortable: false,
    align: 'right',
    _total: 'sum',
  },
  {
    title: 'Доп.точки',
    value: 'additionalPointsSum',
    sortable: false,
    align: 'right',
    _total: 'sum',
  },
  {
    title: 'Доплата',
    value: 'payment',
    sortable: false,
    align: 'right',
    _total: 'sum',
  },
  {
    title: 'Итого',
    value: 'totalSum',
    sortable: false,
    align: 'right',
    _total: 'sum',
  },
  {
    title: 'Часы',
    value: 'duration',
    sortable: false,
    align: 'right',
    width: '45px',
    _total: 'sum',
  },
  { title: 'Оценка', value: 'grade.grade', sortable: false, align: 'right' },
  { title: 'Комментарий к оценке', value: 'grade.note', sortable: false },
]
