export const ALL_HEADERS = [
  {
    value: 'orderDate',
    title: 'Дата рейса',
    sortable: false,
    width: '12rem',
    default: true,
    groupable: false,
  },
  {
    value: 'orderTypeStr',
    title: 'Тип рейса',
    sortable: true,
    width: '7rem',
    default: true,
    groupable: true,
  },
  {
    value: 'tkNameStr',
    title: 'TK',
    sortable: false,
    width: '9rem',
    default: true,
    groupable: false,
  },

  {
    value: 'truckNumStr',
    title: 'Грузовик',
    sortable: false,
    align: 'center',
    width: '9rem',
    default: true,
    groupable: false,
  },
  {
    value: 'trailerNumStr',
    title: 'Прицеп',
    sortable: false,
    align: 'center',
    width: '9rem',
    default: false,
    groupable: false,
  },
  {
    value: 'driverFullName',
    title: 'Водитель',
    sortable: true,
    align: 'left',
    default: true,
    groupable: true,
  },
  {
    value: 'clientName',
    title: 'Клиент',
    sortable: true,
    default: true,
    groupable: true,
  },
  {
    value: 'client.num',
    title: '№ Заказа',
    sortable: false,
    default: true,
    groupable: false,
  },
  {
    value: 'client.auctionNum',
    title: '№ Аукциона',
    sortable: false,
    default: true,
    groupable: false,
  },
  {
    value: 'loadingPoints',
    title: 'Погрузка',
    sortable: false,
    default: true,
    groupable: false,
  },
  {
    value: 'unloadingPoints',
    title: 'Разгрузка',
    sortable: false,
    default: true,
    groupable: false,
  },
  {
    value: 'docsState.date',
    title: 'Дата получения',
    sortable: true,
    default: false,
    groupable: false,
    align: 'right',
  },
  {
    value: 'reviewDate',
    title: 'Дата проверки',
    sortable: true,
    default: false,
    groupable: false,
    align: 'right',
  },
  {
    value: 'getDocsDays',
    title: 'Сдача документов, дней',
    sortable: true,
    default: false,
    groupable: false,
    align: 'right',
  },
  {
    value: 'reviewDocsDays',
    title: 'Проверка документов, дней',
    sortable: true,
    default: false,
    groupable: false,
    align: 'right',
  },
  {
    value: '_docsStatusObj.text',
    title: 'Документы',
    sortable: true,
    default: true,
  },
]

/* --------------------------------

  {
    value: 'loadingZones',
    title: 'Зоны погрузки',
    sortable: false,
    default: false,
  },

  {
    value: 'agreement.name',
    title: 'Соглашение',
    sortable: false,
    forAccountingMode: true,
    default: true,
  },

  {
    value: 'actions',
    // title: 'Действия',
    sortable: false,
    forAccountingMode: true,
    width: '3rem',
    default: true,
  },


*/
