export const PIVOT_HEADERS = [
  { value: '_rowNumber', sortable: false, width: '30px', align: 'right' },
  { text: 'Водитель', value: '_driverName', sortable: false, width: '350px' },
  {
    text: 'Рейсы',
    value: '_count',
    sortable: true,
    width: '100px',
    align: 'right',
    _total: 'sum',
    field: 'totalCount',
  },
  {
    text: 'Часы',
    value: 'duration',
    sortable: true,
    width: '100px',
    align: 'right',
    // _total: 'sum',
  },
  {
    text: 'Ставка',
    value: 'base',
    sortable: true,
    width: '100px',
    align: 'right',
    _total: 'sum',
  },
  {
    text: 'Простой',
    value: 'waiting',
    sortable: true,
    width: '100px',
    align: 'right',
    _total: 'sum',
  },
  {
    text: 'Доплата',
    value: 'payment',
    sortable: true,
    width: '100px',
    align: 'right',
    _total: 'sum',
  },
  {
    text: 'Возврат',
    value: 'returnSum',
    sortable: true,
    align: 'right',
    width: '100px',
    _total: 'sum',
  },
  {
    text: 'Доп.точки',
    value: 'additionalPointsSum',
    sortable: true,
    align: 'right',
    width: '100px',
    _total: 'sum',
  },
  {
    text: 'Итого',
    value: 'totalSum',
    sortable: true,
    align: 'right',
    width: '120px',
    _total: 'sum',
  },
  {
    text: 'Оценка',
    value: 'avgGrade',
    sortable: true,
    width: '100px',
    align: 'right',
  },
  {
    value: 'padding',
    width: '20px',
    sortable: false,
  },
]

export const DRIVER_DETAILS_HEADERS = [
  { value: '_rowNumber', sortable: false, width: '30px', align: 'right' },
  { text: 'Дата рейса', value: '_orderDate', sortable: false },
  { text: 'Грузовик', value: '_truckRegNum', sortable: false },
  { text: 'Прицеп', value: '_trailerRegNum', sortable: false },
  { text: 'Клиент', value: '_client.name', sortable: false },
  { text: 'Погрузка', value: '_loadingAddressesStr', sortable: false },
  { text: 'Выгрузка', value: '_unloadingAddressesStr', sortable: false },
  {
    text: 'Тип грузополучателя',
    value: '_consigneeType.text',
    sortable: false,
  },
  {
    text: 'Тип базового тарифа',
    value: '_baseTariffTypeStr',
    sortable: false,
  },
  {
    text: 'База',
    value: 'baseTariff.tariff.sum',
    sortable: false,
    align: 'right',
  },
  { text: 'Простой', value: 'waitingSum', sortable: false, align: 'right' },
  { text: 'Возврат', value: 'returnSum', sortable: false, align: 'right' },
  {
    text: 'Доп.точки',
    value: '_additionalPointsSum',
    sortable: false,
    align: 'right',
  },
  { text: 'Доплата', value: '_paymentSum', sortable: false, align: 'right' },
  { text: 'Итого', value: '_totalSum', sortable: false, align: 'right' },
  {
    text: 'Часы',
    value: '_routeDuration',
    sortable: false,
    align: 'right',
    width: '45px',
  },
  { text: 'Оценка', value: 'grade.grade', sortable: false, align: 'right' },
  { text: 'Комментарий к оценке', value: 'grade.note', sortable: false },
]
