export const ALL_HEADERS = [
  {
    value: 'plannedDateStr',
    text: 'Дата рейса',
    sortable: true,
    width: '12rem',
    default: true,
    groupable: false,
  },
  {
    value: 'orderTypeStr',
    text: 'Тип рейса',
    sortable: false,
    width: '7rem',
    default: true,
    groupable: false,
  },
  {
    value: 'tkNameStr',
    text: 'TK',
    sortable: false,
    width: '9rem',
    default: true,
    groupable: false,
  },

  {
    value: 'truckNumStr',
    text: 'Грузовик',
    sortable: false,
    align: 'center',
    width: '9rem',
    default: true,
    groupable: false,
  },
  {
    value: 'trailerNumStr',
    text: 'Прицеп',
    sortable: false,
    align: 'center',
    width: '9rem',
    default: false,
    groupable: false,
  },
  {
    value: 'driverFullName',
    text: 'Водитель',
    sortable: false,
    align: 'left',
    default: true,
    groupable: false,
  },
  {
    value: 'clientName',
    text: 'Клиент',
    sortable: false,
    default: false,
    groupable: false,
  },
  {
    value: 'clientNum',
    text: '№ Заказа',
    sortable: false,
    default: true,
    groupable: false,
  },
  {
    value: 'agreementName',
    text: 'Соглашение',
    sortable: false,
    default: true,
    groupable: false,
  },
  {
    value: 'clientAuctionNum',
    text: '№ Аукциона',
    sortable: false,
    default: false,
    groupable: false,
  },
  {
    value: 'loadingPoints',
    text: 'Погрузка',
    sortable: false,
    default: true,
    groupable: false,
  },
  {
    value: 'unloadingPoints',
    text: 'Разгрузка',
    sortable: false,
    default: true,
    groupable: false,
  },
  {
    value: 'docsStatusStr',
    text: 'Документы',
    sortable: false,
    default: false,
    groupable: false,
  },
  {
    value: 'itemType',
    text: 'Тип записи',
    sortable: false,
    default: false,
    groupable: false,
  },
  {
    value: 'basePriceWOvat',
    text: 'Тариф без НДС',
    sortable: false,
    align: 'right',
    default: false,
    groupable: false,
  },
  {
    value: 'basePrice',
    text: 'Тариф c НДС',
    sortable: false,
    align: 'right',
    default: false,
    groupable: false,
  },
  {
    value: 'additionalPriceWOvat',
    text: 'Доп.доход без НДС',
    sortable: false,
    default: false,
    align: 'right',
    groupable: false,
  },
  {
    value: 'additionalPrice',
    text: 'Доп.доход с НДС',
    sortable: false,
    align: 'right',
    default: false,
    groupable: false,
  },
  {
    value: 'totalPriceWOvat',
    text: 'Итог без НДС',
    sortable: true,
    align: 'right',
    groupable: false,
    default: true,
  },
  {
    value: 'totalPrice',
    text: 'Итог с НДС',
    sortable: true,
    align: 'right',
    default: true,
    groupable: false,
  },
]
