export const ALL_HEADERS = [
  {
    value: 'orderDate',
    text: 'Дата рейса',
    sortable: false,
    width: '12rem',
    default: true,
    groupable: false,
  },
  {
    value: 'orderTypeStr',
    text: 'Тип рейса',
    sortable: true,
    width: '7rem',
    default: true,
    groupable: true,
  },
  {
    value: 'tkNameStr',
    text: 'TK',
    sortable: false,
    width: '9rem',
    default: true,
    groupable: false,
  },

  {
    value: 'truckNumStr',
    text: 'Грузовик',
    sortable: false,
    align: 'center',
    width: '9rem',
    default: true,
    groupable: false,
  },
  {
    value: 'trailerNumStr',
    text: 'Прицеп',
    sortable: false,
    align: 'center',
    width: '9rem',
    default: false,
    groupable: false,
  },
  {
    value: 'driverFullName',
    text: 'Водитель',
    sortable: true,
    align: 'left',
    default: true,
    groupable: true,
  },
  {
    value: 'clientName',
    text: 'Клиент',
    sortable: true,
    default: true,
    groupable: true,
  },

  {
    value: 'loadingPoints',
    text: 'Погрузка',
    sortable: false,
    default: true,
    groupable: false,
  },
  {
    value: 'unloadingPoints',
    text: 'Разгрузка',
    sortable: false,
    default: true,
    groupable: false,
  },
  {
    value: '_docsStatusObj.text',
    text: 'Документы',
    sortable: true,
    default: true,
  },
]
