export default [
  {
    value: 'number',
    title: 'Номер',
    sortable: true,
    default: true,
  },
  {
    value: 'date',
    title: 'Дата акта',
    sortable: true,
    default: true,
    align: 'center',
  },
  {
    value: 'receiptDate',
    title: 'Дата получения',
    sortable: true,
    default: true,
    align: 'center',
  },
  {
    value: 'plannedPayDate',
    title: 'Плановая дата оплаты',
    sortable: true,
    default: true,
    align: 'center',
  },
  {
    value: 'payDate',
    title: 'Дата оплаты',
    sortable: true,
    default: true,
    align: 'center',
  },
  {
    value: 'status',
    title: 'Статус',
    sortable: false,
    default: true,
  },
  {
    value: 'agreementName',
    title: 'Соглашение',
    sortable: false,
    default: true,
  },
  {
    value: 'carrierName',
    title: 'Перевозчик',
    sortable: false,
    default: true,
  },
  {
    value: 'ordersCount',
    title: 'Кол-во рейсов',
    sortable: true,
    default: false,
    align: 'right',
    width: '10rem',
  },
  {
    value: 'priceWOVat',
    title: 'Сумма без НДС',
    sortable: true,
    default: true,
    align: 'right',
    width: '10rem',
  },

  {
    value: 'priceWithVat',
    title: 'Сумма',
    sortable: true,
    default: false,
    align: 'right',
    width: '10rem',
  },
  {
    value: 'note',
    title: 'Примечание',
    sortable: false,
    default: true,
  },
]
