export default [
  {
    title: '№',
    value: 'idx',
    align: 'right',
    width: '2rem',
    sortable: false,
  },
  {
    title: '№ Рейса',
    value: 'routeNumber',
    sortable: false,
    align: 'center',
    default: true,
    width: '4rem',
  },
  {
    title: 'Площадка',
    value: 'placeName',
    align: 'center',
    sortable: false,
    width: '10rem',
  },
  {
    value: 'orderDate',
    title: 'Дата',
    sortable: false,
    align: 'center',
    width: '10rem',
    default: true,
  },
  {
    value: 'docNumbers',
    title: 'Номера документов',
    sortable: false,
    default: true,
  },
  {
    value: 'driverName',
    title: 'Водитель',
    sortable: false,
    align: 'left',
    default: true,
    width: '20rem',
  },

  {
    title: 'Сопроводительные док-ты',
    value: 'docTypesStr',
    sortable: false,
    default: true,
  },
  {
    title: 'Примечание',
    value: 'note',
    sortable: false,
    width: '10rem',
    default: true,
  },
  // {
  //   value: 'actions',
  //   sortable: false,
  //   width: '2rem',
  //   default: true,
  //   align: 'center',
  // },
  // {
  //   value: 'analytics.type',
  //   title: 'Тип рейса',
  //   sortable: false,
  //   width: '7rem',
  //   default: true,
  // },
  // {
  //   value: 'tk',
  //   title: 'TK',
  //   sortable: false,
  //   width: '9rem',
  //   default: true,
  // },

  // {
  //   value: 'truck',
  //   title: 'Грузовик',
  //   sortable: true,
  //   align: 'center',
  //   width: '9rem',
  //   default: true,
  // },
  // {
  //   value: 'trailer',
  //   title: 'Прицеп',
  //   sortable: false,
  //   align: 'center',
  //   width: '9rem',
  //   default: false,
  // },
  //
  // {
  //   value: 'loadingZones',
  //   title: 'Зоны погрузки',
  //   sortable: false,
  //   default: false,
  // },
  // {
  //   value: 'loadingPoints',
  //   title: 'Погрузка',
  //   sortable: false,
  //   default: true,
  // },
  // {
  //   value: 'unloadingPoints',
  //   title: 'Разгрузка',
  //   sortable: false,
  //   default: true,
  // },
  // { value: 'state.status', title: 'Статус', sortable: false, default: true },
  // { value: 'client.client', title: 'Клиент', sortable: false, default: true },
  // {
  //   value: 'client.num',
  //   title: '№ Заказа',
  //   sortable: false,
  //   default: true,
  // },
  // {
  //   value: 'client.auctionNum',
  //   title: '№ Аукциона',
  //   sortable: false,
  //   default: true,
  // },

  // {
  //   value: 'agreement.name',
  //   title: 'Соглашение',
  //   sortable: false,
  //   forAccountingMode: true,
  //   default: true,
  // },
  // {
  //   value: 'docsGetted',
  //   title: 'Сданы',
  //   sortable: false,
  //   forAccountingMode: true,
  //   default: true,
  // },
  // {
  //   value: 'docStatus',
  //   title: 'Документы',
  //   sortable: false,
  //   default: true,
  // },
  //
]
