export const allHeaders = [
  { value: 'order', title: 'Индекс', width: '3rem', sortable: false },
  { value: 'tkName.name', title: 'ТК' },
  { value: 'type', title: 'Тип' },
  { value: 'regNum', title: 'Гос.номер', width: '10rem' },
  {
    value: 'liftCapacityType',
    title: 'Груз-cть, т',
    width: '6rem',
    sortable: false,
    align: 'center',
  },
  { value: 'pltCount', title: 'Плт', width: '6rem', sortable: false, align: 'center' },
  { value: 'brand', title: 'Марка' },
  { value: 'currentDriver', title: 'Водитель' },
  {
    value: 'permanentDriverCount',
    title: 'Закреп. водители',
    align: 'center',
    width: '7rem',
    sortable: false,
  },
  {
    value: 'temporaryDriverCount',
    title: 'Времен. водители',
    align: 'center',
    width: '7rem',
    sortable: false,
  },
  { value: 'additionalDetails.transponderNumber', title: 'Транспондер', align: 'center' },
  { value: 'additionalDetails.platonNumber', title: 'Платон', align: 'center' },
  { value: 'additionalDetails.fuelCardNumber', title: 'Топл.карта', align: 'center' },
  { value: 'sts', title: 'СТС', align: 'center' },
  { value: 'win', title: 'ВИН', align: 'center' },
  { value: 'owner', title: 'Собственник', align: 'center' },
  { value: 'issueYear', title: 'Год выпуска', align: 'center' },
  { value: 'brigadier', title: 'Бригадир' },
  { value: 'hasScans', title: 'Есть сканы', sortable: false, width: '5rem', align: 'center' },
]
