name: Docker Image CI (__PROD__)
on:
  pull_request:
    types:
      - closed
    branches: ['main']
env:
  VITE_API_URL: https://s4log.ru/api
  VITE_API_WS_URL: https://s4log.ru
  VITE_STATIC_URL: https://s4log.ru
jobs:
  build:
    if: github.event.pull_request.merged == true
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3
        with:
          ref: main

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/front:latest
